---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[postgresql::default]
    attributes:
