---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[prey_meetup::default]
    attributes:
  - name: server
    run_list:
      - recipe[prey_meetup::server]

