name: irssi
version: "1.0.0"
summary: IRSSI IRC Client
description: foo
confinement: strict

apps:
  irssi:
    command: irssi

parts:
  irssi:
    plugin: autotools
    source: https://github.com/irssi/irssi/releases/download/1.0.0/irssi-1.0.0.tar.gz
    build-packages:
      - build-essential
